name: Build and Deploy to EKS
on:
  push:
    branches: ["main"]
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: status-page
  EKS_CLUSTER_NAME: statuspage
permissions:
  id-token: write
  contents: read
jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-image.outputs.image }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::992382545251:role/GitHubActionsRole # Create this role manually or with Terraform
        aws-region: ${{ env.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::992382545251:role/GitHubActionsRole
        aws-region: ${{ env.AWS_REGION }}
    - name: Set up Kubeconfig
      run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
    - name: Deploy to EKS using Kustomize
      run: |
        cd k8s/base
        kustomize edit set image REPLACE_WITH_YOUR_ECR_REPO_URL=${{ needs.build-and-push.outputs.image }}
        kubectl apply -k .
